name: Feature Request
description: Suggest a new feature idea
title: '[FEA]: '
labels: ['Feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is, e.g., "I would like to be able to..."
      placeholder: I would like to be able to perform remote memory allocations and deallocation.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: |
        Implement a `allocateObjectRemote` that has the following signature:

        ```
        T allocateObjectRemote(std::uint64_t num = 1, MemoryType memoryType = MemoryType::Main);
        ```
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the request here.
      placeholder: This would be a helpful high-level function for the distributed array and other data structures.
    validations:
      required: true
